### ISSUE TITLE
Incorrect guess tries counter

### ISSUE THREAD

**Issue by todorm85** [todorm85/Bulls-and-Cows-2#1]
Every time a number is attempted as a guess try and it was already attempted in the same game session, it is counted as a guess try again. For example if 1234 is attempted once and it returns 1 cow, and then the same number 1234 is attempted again it returns 1 cow again and updates the tries counter once more. So the tries counter is updated two times for the same number, which is incorrect.

**Comment by vesheff** [comment]
I think this doesn't need to be changed. It is because the player has the responsibility of keep track of the numbers he already tried.

**Comment by todorm85** [comment]
Ok, so if it should be the player`s responsibility then I think we should implement some history to view all the tried numbers, so the player won`t have to manually write somewhere else all the numbers he/she has tried. Either way, something has to be done, otherwise we have poor UX.

**Comment by vesheff** [comment]
Done.
When user tries the same number again he is notified for this.
