### ISSUE TITLE
DefaultScoreCalculator needs refactoring

### ISSUE THREAD

**Issue by todorm85** [todorm85/Bulls-and-Cows-2#4]
Introduce new classes for file system I/O operations. It is not ScoreCalculator`s job to read/write to file system. It should just save/load results. Remove try/catch code blocks and introduce validation for file existence.

**Comment by vesheff** [comment]
The logic is changed. It just need to be separated in two classes, and the scoreboard must be a strategy pattern.

**Comment by todorm85** [comment]
If I understand you correctly, that`s what I said also. My suggestion is to create a new class for reading/writing to disk (for example - DiskIO), and then through strategy/dependency inversion use it in the ScoreCalculator class. So the strategy will be the new class :) - DiskIO, not the one that is using it to be precise.

**Comment by vesheff** [comment]
This issue is completed.
